name: Auto deploy

on:
  schedule:
    - cron: "45 15 * * *"

jobs:
  auto_deploy:
    uses: moogur/all-workflows/.github/workflows/auto_deploy_for_docker_container.yml@master
    secrets: inherit
    with:
      environment: DEPLOY
      repository_url: "https://github.com/yumata/lampa.git"
      repository_branch: "main"
