name: Auto deploy

on:
  schedule:
    - cron: "0 3 * * 5"

jobs:
  auto_deploy:
    uses: moogur/all-workflows/.github/workflows/auto_deploy_for_build_application.yml@master
    secrets: inherit
    with:
      repository_url: "https://github.com/yumata/lampa.git"
      environment: DEPLOY
      type: "commit"
      repository_branch: "main"
      file_path: "scripts/build.sh"
